### ISSUE TITLE
typo in repo description

### ISSUE THREAD

**Issue by knightnemo** [youkaichao/youkaichao#3]
<img width="1267" alt="image" src="https://github.com/user-attachments/assets/326174c2-18f5-4c22-848c-e9e8f9cea298" />
Huge fan of your work, found this typo is your github profile repo, "progile" lol

**Comment by youkaichao** [comment]
thanks for taking care of it :)

I changed the one in the repo description. anywhere else?

**Comment by knightnemo** [comment]
cool;) 
none that I'm aware of.
